apiVersion: v1
kind: Namespace
metadata:
  name: ingresstest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: ingresstest
  labels:
    app: nginx-app
spec:
  containers:
  - image: nginx
    name: nginx-image
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 3
      timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-svc
  namespace: ingresstest
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ext-ingress
  namespace: ingresstest
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /nginxapp
        pathType: Prefix
        backend:
          service:
            name: nginx-app-svc
            port:
              number: 80
