apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  index.html: |
    main page by jacob
  test.html: |
    test page by jacob
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;

        location ^~ /test(.*) {
          alias  /usr/share/nginx/html;
          index  test.html;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
spec:
  selector:
    matchLabels:
      app: nginx-sample
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - image: nginx:latest
        name: nginx-sample
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: index
            mountPath: /usr/share/nginx/html
          - name: config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: index
        configMap:
          name: nginx-cm
      - name: config
        configMap:
          name: nginx-config-cm
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample-svc
spec:
  selector:
    app: nginx-sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
