apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-204-html-cm
data:
  index.html: |
    main page by jacob
  test.html: |
    test page by jacob
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-204-config-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      log_format custom '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';
      access_log /dev/stdout;
      server {
        listen       80;
        server_name  localhost;

        location / {
          return 204;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-204
spec:
  selector:
    matchLabels:
      app: nginx-204
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-204
    spec:
      containers:
      - image: nginx:latest
        name: nginx-204
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: index
            mountPath: /usr/share/nginx/html
          - name: config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: index
        configMap:
          name: nginx-204-html-cm
      - name: config
        configMap:
          name: nginx-204-config-cm
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-204-svc
spec:
  selector:
    app: nginx-204
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    appProtocol: http
