apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-xff-html-cm
data:
  index.html: |
    main page by jacob
  test.html: |
    test page by jacob
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-xff-config-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      log_format  logs_requested  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$request_time" "$upstream_response_time" "$pipe" "$http_x_forwarded_for"';
      server {
        listen       80;
        server_name  localhost;
        access_log  /var/log/nginx/access.log  logs_requested;

        root   /usr/share/nginx/html;
        index  index.html index.htm;

        location ^~ /test(.*) {
          alias  /usr/share/nginx/html;
          index  test.html;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-xff
spec:
  selector:
    matchLabels:
      app: nginx-xff
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-xff
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: index
            mountPath: /usr/share/nginx/html
          - name: config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: index
        configMap:
          name: nginx-xff-html-cm
      - name: config
        configMap:
          name: nginx-xff-config-cm
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-xff-svc
spec:
  selector:
    app: nginx-xff
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
